#!/bin/bash

#http://www.yolinux.com/TUTORIALS/BashShellCgi.html
printf "Content-type: text/plain\n\n"



#/usr/bin/env

first=0


objects=""
entity=""
action=""

objects=$(echo $PATH_INFO | cut -d"/" -f2)
entity=$(echo $PATH_INFO | cut -d"/" -f3)
action=$(echo $PATH_INFO | cut -d"/" -f4)

#echo
#echo "objects $objects entity $entity action $action !"

sql="/tmp/rest.sql"


device=""
cols="host,image,phase,progress,uptime,percentage,state,wlan "

init_table(){
test -f $sql && rm $sql

sql_cmd="create table devices ( avahi, hosttype, $cols );"
#echo $sql_cmd
echo $sql_cmd  | sqlite3 $sql

sql_cmd="insert into devices ( avahi, hosttype, $cols ) values ( 'Avahi', 'Hosttpype', 'Host', 'Image', 'Phase', 'Progress', 'Uptime', 'Battery', 'State', 'Wlan' );"
#echo $sql_cmd
echo $sql_cmd  | sqlite3 $sql
}


#"hosttype $hosttype $hostT $host $imageT $image $phaseT $phase $progressT $progress $uptimeT $uptime $batteryT $battery $stateT $state $wlanT $wlan" 

call_remote(){
    local name=$1
    local aktion=$2

    local addr=$(avahi-resolve -4 -n $name.local 2>/dev/null | xargs | cut -d\  -f2)
    if test -n "$addr" ;then
        if fping -a $addr >/dev/null 2>&1;then
	    wget -O - http://$addr:1649/api/v1/devices/localhost/$aktion 2>/dev/null|xargs
	fi
    fi
 }


get_status(){
    local hostT="host"
    local host=$(hostname)
    local hosttypeT="hosttype"
    local hosttype=$(puavo-conf puavo.hosttype)

    if test "$hosttype" = "laptop";then
       local update=$(cat /images/image_update.stats|xargs)
       local power=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0| \
		      grep "state:\|percentage:"|sed -e "s/://g"|sed -e "s/%//g"|xargs)    
       local wlanT="wlan"
       local wlan=$(iwconfig 2>/dev/null|grep Quality|xargs|cut -d\  -f4|cut -d"=" -f2)
       local uptimeT="uptime"
       local uptime=$(cat /proc/uptime | cut -d" " -f1|cut -d"." -f1)
    
       local imageT=$(echo $update | cut -d" " -f1)
       local image=$(echo $update | cut -d" " -f2)
       local phaseT=$(echo $update | cut -d" " -f3)
       local phase=$(echo $update | cut -d" " -f4)
       local progressT=$(echo $update | cut -d" " -f5)
       local progress=$(echo $update | cut -d" " -f6)
       local batteryT=$(echo $power | cut -d" " -f1)
       local battery=$(echo $power | cut -d" " -f2)
       local stateT=$(echo $power | cut -d" " -f3)
       local state=$(echo $power | cut -d" " -f4)

       local dev="$hosttypeT $hosttype $hostT $host $imageT $image $phaseT $phase $progressT $progress $uptimeT $uptime $batteryT $battery $stateT $state $wlanT $wlan" 
    else
	local dev="$hosttypeT $hosttype $hostT $host"
    fi
    
    echo $dev
}

gv(){
local value=$1
local found=1
for n in $device; do
    if test $found = 0;then echo $n; return;fi
    if test $n = $value; then found=0;fi
done
}
 
show_error(){
    echo "error"
}

get_list(){
    local l=
    local dev=$(ip route|grep default|head -n1|xargs|cut -d\  -f5)
    local liste=$(avahi-browse -at|grep "$dev IPv4 puavo"|xargs|sed -e "s/+ //g"|sed -e "s/local/|/g"|sed -e "s/#/ /g")

    #echo getlist : $liste
    
#    printf "{\n"
    while test -n "$liste";do
        l=$(echo "$liste"|xargs|cut -d"|" -f1)
        liste=$(echo "$liste"|cut -d"|" -f2-)
        if test -n "$l";then 
#	    local hosttype=$(echo $l|xargs|cut -d\  -f4);
	    local hostname=$(echo $l|xargs|cut -d\  -f5);
#	    local profiles=$(echo $l|xargs|cut -d\  -f6);
#	    if test $first = 0; then first=1; else printf ",\n";fi

#            echo   "$hostname :::"
	    device=$(call_remote $hostname "status")  
#            echo $device
#	    echo "ende"
# $cols=" avahi,     host,hosttype,image,phase,progress,uptime,battery,state,wlan "
	    
            local sql_cmd="insert into devices ( avahi, hosttype, $cols ) values ( '$hostname' , '$(gv hosttype)', '$(gv host)', '$(gv image)', '$(gv phase)', '$(gv progress)', '$(gv uptime)', '$(gv percentage)', '$(gv state)', '$(gv wlan)' );"
#	    echo $sql_cmd
	    echo "$sql_cmd" | sqlite3 $sql
	    
	fi
    done
#    printf "\n"
    #    printf "}" ) | base64

    echo "<table>"
    echo "<thead>"
    echo "select $cols from devices where rowid=1"| sqlite3 -html $sql |xargs
    echo "</thead>"
    echo "<tbody>"
    sql_cmd="select $cols from devices where rowid!=1 and hosttype='laptop' order by host;"
    echo $sql_cmd | sqlite3 -html $sql | xargs
    echo "</tbody>"
    echo "</table>"
}

    
case "$objects" in
    devices)
	case "$entity" in
	    localhost)
		case "$action" in
		    update)
			echo /usr/sbin/puavo-update-client ;;
		    reboot)
			test "$SERVER_ADDR" = "$REMOTE_ADDR" || echo /usr/sbin/reboot ;;
		    poweroff)
			test "$SERVER_ADDR" = "$REMOTE_ADDR" -o "$(puavo-conf puavo.hosttype)" = "bootserver" || echo /usr/sbin/halt ;;
		    status)
			get_status ;;
		    "")
			get_status ;;
		    *)
			show_error ;;	    
		esac
	        ;;
	    "")
		init_table
		get_list ;;
	    *)
		case $action in
		    update|poweroff|reboot)
			call_remote $entity $action ;;
		    *) ;;
		esac
	esac
	;;
    *)
	show_error ;;
esac



exit 0

HTTP_ACCEPT_ENCODING=gzip, deflate
SERVER_NAME=zeus-011.basel.opinsys.fi
SCRIPT_NAME=/cgi/env.sh
GATEWAY_INTERFACE=CGI/1.1
SERVER_SOFTWARE=webfs/1.21
PATH_INFO=/uhu/gaga/mmmmmm
DOCUMENT_ROOT=/opt/puavo-update-status
HTTP_UPGRADE_INSECURE_REQUESTS=1
PWD=/
REQUEST_URI=/cgi/env.sh/uhu/gaga/mmmmmm?ooo=iiiiiiiii&uuuu=7
QUERY_STRING=ooo=iiiiiiiii&uuuu=7
HTTP_ACCEPT_LANGUAGE=de,en-US;q=0.7,en;q=0.3
HTTP_ACCEPT=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
REMOTE_PORT=41670
SERVER_ADMIN=root@localhost
HTTP_HOST=localhost:1649
HTTP_CONNECTION=keep-alive
SERVER_ADDR=127.0.0.1
HTTP_USER_AGENT=Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
SHLVL=1
SERVER_PROTOCOL=HTTP/1.1
SERVER_PORT=1649
SCRIPT_FILENAME=/opt/puavo-update-status/cgi/env.sh
REMOTE_ADDR=127.0.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
REQUEST_METHOD=GET
_=/usr/bin/env

#	    printf '   "%b": {' $hostname 
#	    printf '      "hosttype":  "%b",' $hosttype
#	    printf "%b" "\"hosttype\": \"$hosttype\n"
#	    printf '      "profiles": "%b",' $profiles
#	    printf "      \"status\": {\n"
#            call_remote $hostname "status"  
#	    printf "      }"
#	    printf ""
#	    printf "   }"

#    echo '{ \"status\": { "'$hostT'": "'$host'", "'$imageT'": "'$image'", "'$phaseT'": "'$phase'", "'$progressT'": "'$progress'", "'$uptimeT'": "'$uptime'", "'$batteryT'": "'$battery'", "'$stateT'": "'$state'", "'$wlanT'": "'$wlan'" } }' 

#    echo gaga
#    echo $(/usr/bin/jq -n "$json")
#    echo uhu
    
#    echo  '"status": {'
#    printf '         \"host\": \"%q\",\n' $(hostname)
#    printf "         \"%q\": \"%q\",\n" $(echo $update | cut -d" " -f1) $(echo $update|cut -d" " -f2)
#    printf "         \"%q\": \"%q\",\n" $(echo $update | cut -d" " -f3) $(echo $update|cut -d" " -f4)
#    printf "         \"%q\": \"%q\",\n" $(echo $update | cut -d" " -f5) $(echo $update|cut -d" " -f6)
#    printf "         \"%q\": \"%q\",\n" $(echo $power | cut -d" " -f1) $(echo $power|cut -d" " -f2)
#    printf "         \"%q\": \"%q\",\n" $(echo $power | cut -d" " -f3) $(echo $power|cut -d" " -f4)
#    printf "         \"wlan\": \"%q\",\n" $wlan
#    printf "         \"uptime\": \"%q\"\n" $uptime
#    printf "}"

# REQUEST_URI=/cgi/env.sh/uhu/gaga/mmmmmm?ooo=iiiiiiiii&uuuu=7
# SCRIPT_NAME=/cgi/env.sh
# PATH_INFO=/uhu/gaga/mmmmmm
# QUERY_STRING=ooo=iiiiiiiii&uuuu=7
# REMOTE_ADDR=127.0.0.1
# SERVER_ADDR=127.0.0.1

