#!/bin/sh


hosttype=$(puavo-conf puavo.hosttype)
echo $hosttype
case $hosttype in
    laptop|wirelessaccesspoint)
	echo "start webfsd ..."
	/usr/bin/webfsd -4 -p 1649 -r /opt/puavo-update-status -x /cgi -f index.html -j
	;;
    bootserver)
	#start a virtual nginx host
	;;
    *)
	;;
esac

cat <<EOF > /etc/avahi/services/puavo-avahi-publish.service
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
<name replace-wildcards="yes">puavo#$hosttype#%h</name>
<service>
<type>_ssh._tcp</type>
<port>22</port>
</service>
</service-group>
EOF

systemctl restart avahi-daemon.service

sleep 9999999999999999999999999999999

