#!/bin/sh


hosttype=$(puavo-conf puavo.hosttype)
list=$(puavo-conf puavo.profiles.list)

#case $hosttype in
#    laptop|wirelessaccesspoint|fatclient)
	echo "start webfsd ..."
	/usr/bin/webfsd -4 -p 1649 -r /opt/puavo-update-status -x /api -f index.html -j
#	;;
#    bootserver)
#	# /usr/bin/sed -e "s/#host-name=foo/host-name=puavobox/g" -i /etc/avahi/avahi-daemon.conf
#	;;
#    *)
#	;;
#esac

cat <<EOF > /etc/avahi/services/puavo-avahi-publish.service
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
<name replace-wildcards="yes">puavo $hosttype %h $list</name>
<service>
<type>_ssh._tcp</type>
<port>22</port>
</service>
</service-group>
EOF

systemctl restart avahi-daemon.service

sleep 9999999999999999999999999999999

