#!/bin/sh


hosttype=$(puavo-conf puavo.hosttype)


cat <<EOF > /etc/avahi/services/puavo-avahi-publish.service
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
<name replace-wildcards="yes">puavo $hosttype %h</name>
<service>
<type>_ssh._tcp</type>
<port>22</port>
</service>
</service-group>
EOF

systemctl restart avahi-daemon.service



